name: LoxPHP

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ 8.3 ]
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: composer run-script test
